version: '3.3'
services:
  results.mysql:
    container_name: results.mysql
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        aliases:
          - results.mysql

  results.app:
    container_name: results.app
    image: mokocchi/dehia-results:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    restart: on-failure
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      SITE_BASE_URL: ${SITE_BASE_URL}
      AUTH_BASE_URL: ${AUTH_BASE_URL}
      DEFINE_BASE_URL: ${DEFINE_BASE_URL}
      COLLECT_BASE_URL: ${COLLECT_BASE_URL}
      WAIT_HOSTS: ${DATABASE_HOST}:3306
      WAIT_SLEEP_INTERVAL: 10
      WAIT_BEFORE: 10
      WAIT_TIMEOUT: 350
    depends_on: 
      - ${DATABASE_HOST}
    expose:
      - 80
    networks: 
      backend:
      dehia:
        aliases:
          - results.app

networks:
  dehia:
    external: true
  backend:
    external: false