version: '3.3'
services:
 results.php:
   volumes:
     - './app:/usr/src/app'

 results.nginx:
   volumes:
     - './app/public/:/usr/src/app'
     - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

 results.adminer:
   ports:
     - '${ADMINER_PORT}:8080'