version: '3.3'
services:
  results.mysql:
    container_name: results.mysql
    image: mysql:8.0
    restart: on-failure
    expose: 
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        aliases:
          - results.mysql

  results.php:
    container_name: results.php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    user: ${LOCAL_USER}
    expose: 
      - 9000
    networks: 
      dehia:
      backend:
        aliases:
          - results.php

  results.nginx:
    container_name: results.nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - results.php
    networks:
      backend:
      dehia:
        aliases:
          - results.nginx

  results.adminer:
    container_name: results.adminer
    image: adminer
    restart: on-failure
    networks: 
      - backend

networks:
  dehia:
    external: true
  backend:
    external: false