v1_controllers:
    resource: ../src/Controller/v1
    type: annotation
    prefix: "/api/v1.0"
    defaults:
        _format: json

v1_public_controllers:
    resource: ../src/Controller/v1/pub
    type: annotation
    prefix: "/api/v1.0/public"
    defaults:
        _format: json